
#' Generates the sequence of dates between specified columns
#'
#' @param dataframe A data frame containing date columns used to find the dates between
#' @param start The column containing the start date
#' @param end The column containing the end date
#' @param sequence_name The name of the output column containing the sequence of dates
#'
#' @returns A data frame with a columns containing the dates between the specified columns
#' @export
#'
#' @examples
date_sequence <- function(dataframe, start, end, sequence_name = "date_sequence") {
  dataframe |>
    dplyr::rowwise() |>
    dplyr::mutate(
      !!rlang::sym(sequence_name) := list(seq(.data[[start]], .data[[end]], by = "day"))
    ) |>
    dplyr::ungroup() |>
    print()
}


#' Finds variable values associated with a list of dates from an environmental data set
#'
#' @param data A data frame containing a columns with date sequences to be assigned such as those generated by the date_sequence() function
#' @param environmental_data A data frame containing the corresponding environmental data to assign
#' @param date_sequence_column The column in data which contains the sequence of dates for each row
#' @param environment_date_column The column in the environmental data frame which contains the dates the variables were recorded on
#' @param environment_variable_column The column of the environmental data frame which contains the variable of interest to assign
#' @param variable_column The output column to assign the assigned environmental data to
#' @param data_fct_col If the data frame contains information from different environments, such as different nest, the column containing the specifying factor
#' @param env_fct_col The column specifying the factor specifying the developmental environment if multiple developmental environments are used
#'
#' @returns A data frame containing a column with the assigned environmental data in each row
#' @export
#'
#' @examples
find_factored_measurements = function(data, environmental_data, date_sequence_column = "date_sequence", environment_date_column, environment_variable_column, variable_column = "variable_values", data_fct_col = NA, env_fct_col = NA) {
  data |>
    dplyr::rowwise() |>
    dplyr::mutate(
      !!rlang::sym(variable_column) := list(purrr::map(.data[[date_sequence_column]], function(dates) {
        if(!is.na(data_fct_col)) {
          factor_id = .data[[data_fct_col]]
        } else {
          factor_id = "NA"
        }

        environmental_data = environmental_data |>
          dplyr::filter(if (!is.na(env_fct_col)) {.data[[env_fct_col]] == factor_id}else {TRUE})

        row_indices <- match(dates, environmental_data[[environment_date_column]])

        as.numeric(environmental_data[[environment_variable_column]][row_indices]) # Convert to numeric

      }))
    ) |>
    dplyr::ungroup() |>
    print()
}


#' Generating values from the assigned data sequence
#'
#' @param dataframe A data frame containing assigned developmental environment data such as those generated by find_factored_measurements()
#' @param column_name The column containing the assigned data
#' @param prefix A prefix for the output column name
#' @param unit A unit for the output column name
#'
#' @returns A data frame containing distribution data of assigned variable
#' @export
#'
#' @examples
generate_values = function(dataframe, column_name = "variable_values", prefix = NA, unit = NA) {

  avg_variable = "avg_variable"
  max_variable = "max_variable"
  min_variable = "min_variable"

  if (!is.na(prefix)) {
    avg_variable = paste0(prefix,"_avg")
    max_variable = paste0(prefix,"_max")
    min_variable = paste0(prefix,"_min")
  }

  if(!is.na(unit)) {
    avg_variable = paste0(avg_variable,"_",unit)
    max_variable = paste0(max_variable,"_",unit)
    min_variable = paste0(min_variable,"_",unit)
  }

  dataframe |>
    dplyr::mutate(
      !!avg_variable := purrr::map_dbl(.data[[column_name]], ~ mean(as.numeric(.x))),
      !!max_variable := purrr::map_dbl(.data[[column_name]], ~ max(as.numeric(.x))),
      !!min_variable := purrr::map_dbl(.data[[column_name]], ~ min(as.numeric(.x)))
    ) |>
    print()
}


